### ISSUE TITLE
1.0.8+ causes a "FATAL ERROR: JS Allocation failed - process out of memory" during runtime

### ISSUE THREAD

**Issue by mxab** [pbastowski/angular-meteor-babel#18] opened 2016-03-29 13:06 UTC
Hi,
we are currently trying to update our project to angular-meteor 1.3

there is something really strange happening if I use angular-babel above 1.0.7

The startup looks normal, but as soon as I open the page with an authenticated user the application loads for some time and then the server gets killed and restarted with the error mentioned in the title.

If I open the page with an anonymous user the page loads normal

Any ideas what might cause this?

**Comment by mxab** [comment] 2016-03-29 13:48
ok i debugged some more it kind of looks like the polyfill does again strange stuff after I added `promise` package before the angular-babel it seems to work again...

**Comment by pbastowski** [comment] 2016-03-29 15:27
Hi @mxab 

So, if you change the order then it works fine again? Is that what you're saying?

What is the correct order that works for you?

BTW, I have released angular-babel@1.3.1 specifically for Meteor 1.3.

**Comment by mxab** [comment] 2016-03-29 15:31
Hi,
initially I had promise not added at all. I just saw during the debugging that there is then some polyfilling from the babel side.
after I added the meteor promise package it worked

I'm using the 1.3.1 package already now. I mentioned the 1.0.8 version only because this was the first version that caused that issue

**Comment by mxab** [comment] 2016-03-29 15:32
This seems to work for me

```
promise
pbastowski:angular-babel@1.3.1
...
```

**Comment by pbastowski** [comment] 2016-03-29 19:10
@mxab 
I've just pushed v1.3.2, with a change that reverts a regression that occurred somewhere along the way. The required functionality was to overwrite the default regenerator runtime supplied by Meteor, because it does not support async/await and some other stuff, with a custom version, which does. 

So, that's back to the way it was and now I'm curious to see if it helps you. I know you already solved this, but I was hoping that this might help. Could you please check and let me know of it helps or stuffs things up.

Thanks.

**Comment by mxab** [comment] 2016-03-29 19:22
Hi,
just tried it unfortunately the it is still stuck as soon as I move the promise dependency after angular babel (1.3.2)

**Comment by pbastowski** [comment] 2016-03-29 19:32
Ok, thanks for trying. At least it does not make things worse :)

**Comment by mxab** [comment] 2016-03-29 19:36
sure :)

**Comment by pbastowski** [comment] 2016-05-16 09:26
Closing this issue, as I don't know how to fix it atm and there is a workaround.

**Closed as completed by pbastowski** 2016-05-16 09:26 UTC
